import type { ChildProfile, RiseStore, SessionLog, Tutor } from "../types/rise";

export const mockTutor: Tutor = {
  id: "tutor-elena",
  fullName: "Elena Dragan",
  email: "elena@risetutoring.co.uk",
};

const now = new Date().toISOString();

export const mockChildren: ChildProfile[] = [
  {
    id: "ayaan-khan",
    tutorKey: "RISE-AK47",
    fullName: "Ayaan Khan",
    preferredName: "Ayaan",
    age: 15,
    pronouns: "he/him",
    yearGroup: "Year 10",
    school: "Northbridge Academy",
    subjects: ["GCSE Physics", "Maths"],
    examBoard: "AQA",
    currentWorkingLevel: "Grade 5",
    targetLevel: "Grade 7",
    mainGoals: "Build exam confidence and secure Grade 7 across Physics problem-solving.",
    confidenceLevel: 3,
    strengths: ["Visual reasoning", "Algebraic fluency", "Good recall after examples"],
    struggles: ["Interference patterns", "Explaining current direction", "Rushing signs in equations"],
    currentTopics: ["Wave Optics", "Interference", "EM Induction"],
    learningStyle: "Visual examples followed by short independent practice.",
    parentName: "Zara Khan",
    parentEmail: "zara.khan@example.com",
    parentPhone: "+44 7700 900234",
    preferredReportMethod: "email",
    currentHomework: "Exam-style EM induction questions 1-8.",
    upcomingTestDate: "2026-06-12",
    longTermGoal: "Secure GCSE Grade 7 in Physics.",
    sessionFrequency: "Weekly",
    tutorNotes: "Responds well when abstract physics is linked to diagrams.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sarah-miller",
    tutorKey: "RISE-SM99",
    fullName: "Sarah Miller",
    yearGroup: "Year 11",
    subjects: ["English Literature"],
    currentWorkingLevel: "Grade 4",
    targetLevel: "Grade 6",
    mainGoals: "Improve essay structure and confidence with Macbeth analysis.",
    confidenceLevel: 2,
    strengths: ["Verbal ideas", "Theme recall"],
    struggles: ["Embedding quotations", "Timed essays"],
    currentTopics: ["Macbeth", "Power and conflict poetry"],
    parentName: "Helen Miller",
    parentEmail: "helen.miller@example.com",
    preferredReportMethod: "pdf",
    sessionFrequency: "Twice weekly",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "leo-chen",
    tutorKey: "RISE-LC12",
    fullName: "Leo Chen",
    yearGroup: "Year 8",
    subjects: ["Chemistry"],
    currentWorkingLevel: "Grade 6",
    targetLevel: "Grade 8",
    mainGoals: "Stretch toward high-grade Chemistry reasoning.",
    confidenceLevel: 4,
    strengths: ["Pattern spotting", "Organic structures"],
    struggles: ["Written explanations"],
    currentTopics: ["Bonding", "Organic chemistry"],
    parentName: "Mei Chen",
    parentEmail: "mei.chen@example.com",
    preferredReportMethod: "email",
    sessionFrequency: "Weekly",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockSessions: SessionLog[] = [
  {
    id: "session-ak-wave-optics",
    childId: "ayaan-khan",
    tutorId: "tutor-elena",
    sessionDate: "2026-05-12",
    topic: "Wave Optics",
    quickNotes: "Struggled with interference patterns. Required visual aids.",
    sessionFocus: ["Weak area support"],
    understandingToday: "guided",
    effortEngagement: 4,
    keySkillWorkedOn: "Understanding concepts",
    homeworkStatus: "reviewed-today",
    nextLessonFocus: ["Review topic"],
    progressRating: 2,
    confidenceRating: 2,
    reportTone: "balanced",
    includeInReport: {
      progressRating: true,
      confidenceRating: true,
      homework: true,
      nextSteps: true,
      previousSessionComparison: true,
    },
    createdAt: "2026-05-12T16:00:00.000Z",
  },
  {
    id: "session-ak-interference",
    childId: "ayaan-khan",
    tutorId: "tutor-elena",
    sessionDate: "2026-05-18",
    topic: "Interference",
    quickNotes: "Improved with diagrams and short guided examples.",
    sessionFocus: ["Revision"],
    understandingToday: "mostly-independent",
    effortEngagement: 4,
    keySkillWorkedOn: "Problem solving",
    homeworkStatus: "set-today",
    homeworkDetails: "Short interference practice set.",
    nextLessonFocus: ["New topic"],
    progressRating: 3,
    confidenceRating: 3,
    reportTone: "balanced",
    includeInReport: {
      progressRating: true,
      confidenceRating: true,
      homework: true,
      nextSteps: true,
      previousSessionComparison: true,
    },
    createdAt: "2026-05-18T16:00:00.000Z",
  },
  {
    id: "session-ak-em-induction",
    childId: "ayaan-khan",
    tutorId: "tutor-elena",
    sessionDate: "2026-05-24",
    topic: "EM Induction",
    quickNotes: "Today's session focus. Guided start, then stronger independent reasoning.",
    sessionFocus: ["New topic"],
    understandingToday: "guided",
    effortEngagement: 4,
    keySkillWorkedOn: "Applying formulas",
    homeworkStatus: "set-today",
    homeworkDetails: "Exam-style EM induction questions 1-8.",
    nextLessonFocus: ["Review topic"],
    progressRating: 3,
    confidenceRating: 3,
    reportTone: "balanced",
    includeInReport: {
      progressRating: true,
      confidenceRating: true,
      homework: true,
      nextSteps: true,
      previousSessionComparison: true,
    },
    createdAt: "2026-05-24T16:00:00.000Z",
  },
];

export const initialRiseStore: RiseStore = {
  tutor: mockTutor,
  children: mockChildren,
  sessions: mockSessions,
  reports: [],
};
